trials: 10
n_cores: -1 # -1=auto

# solve a distribution of problems
problems:
  - env: unicycle1_v0/bugtrap_0
    guess: unicycle1_v0/bugtrap_0/delta_03_v0

  - env: unicycle1_v0/bugtrap_0
    guess: unicycle1_v0/bugtrap_0/delta_02_v0
  #
  - env: unicycle1_v0/bugtrap_0
    guess: unicycle1_v0/bugtrap_0/delta_13_v1

  - env: unicycle1_v0/bugtrap_0
    guess: unicycle1_v0/bugtrap_0/delta_10_v0

  - env: unicycle1_v0/bugtrap_0
    guess: unicycle1_v0/bugtrap_0/delta_05_v0
  #
  - env: unicycle2_v0/bugtrap_0
    guess: unicycle2_v0/bugtrap_0/delta_02_v0
  #
  - env: unicycle2_v0/bugtrap_0
    guess: unicycle2_v0/bugtrap_0/delta_03_v0

  - env: unicycle2_v0/bugtrap_0
    guess: unicycle2_v0/bugtrap_0/delta_05_v0

  - env: unicycle2_v0/bugtrap_0
    guess: unicycle2_v0/bugtrap_0/delta_10_v0

  - env: unicycle2_v0/bugtrap_0
    guess: unicycle2_v0/bugtrap_0/delta_15_v0

  - env: quad2d_v0/quad_bugtrap
    guess: quad2d/bugtrap/delta_05_v0

  - env: quad2d_v0/quad_bugtrap
    guess: quad2d/bugtrap/delta_04_v0

  - env: quad2d_v0/quad_bugtrap
    guess: quad2d/bugtrap/delta_10_v0

  - env: quad2d_v0/quad_bugtrap
    guess: quad2d/bugtrap/delta_20_v0

  - env: quad2d_v0/quad_bugtrap
    guess: quad2d/bugtrap/delta_15_v0

  - env: quad2d_v0/quad2d_recovery_wo_obs
    guess: quad2d/recovery_wo_obs/delta_03_v0

  - env: quad2d_v0/quad2d_recovery_wo_obs
    guess: quad2d/recovery_wo_obs/delta_04_v0

  - env: quad2d_v0/quad2d_recovery_wo_obs
    guess: quad2d/recovery_wo_obs/delta_05_v0

  - env: quad2d_v0/quad2d_recovery_wo_obs
    guess: quad2d/recovery_wo_obs/delta_08_v0

  - env: quad2d_v0/quad2d_recovery_wo_obs
    guess: quad2d/recovery_wo_obs/delta_10_v0

  - env: quad2d_v0/quad2d_recovery_wo_obs
    guess: quad2d/recovery_wo_obs/delta_15_v0

  - env: quadrotor_v0/window
    guess: quadrotor_v0/window/delta_05_v0

  - env: quadrotor_v0/window
    guess: quadrotor_v0/window/delta_06_v0
  #
  - env: quadrotor_v0/window
    guess: quadrotor_v0/window/delta_15_v0
  #
  - env: quadrotor_v0/window
    guess: quadrotor_v0/window/delta_08_v0

  - env: quadrotor_v0/recovery
    guess: quadrotor_v0/recovery/delta_05_v0

  - env: quadrotor_v0/recovery
    guess: quadrotor_v0/recovery/delta_06_v0

  - env: quadrotor_v0/recovery
    guess: quadrotor_v0/recovery/delta_07_v0

  - env: quadrotor_v0/recovery
    guess: quadrotor_v0/recovery/delta_08_v0

  - env: quadrotor_v0/recovery
    guess: quadrotor_v0/recovery/delta_10_v0

  - env: quadrotor_v0/recovery
    guess: quadrotor_v0/recovery/delta_15_v0

algs:

  # - idbastar_v0_fixedtime
  - idbastar_v0_freetime
  - idbastar_v0_freetime_mim
  # - idbastar_v0_mpc
  # - idbastar_v0_mpcc
  # - idbastar_v0_search
