date: 2023-10-24--14-54-32
hostname: fourier
input:
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_03_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_03_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_03_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_03_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_03_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_02_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_02_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_02_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_02_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_02_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_13_v1/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_13_v1/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_13_v1/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_13_v1/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_13_v1/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_10_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_10_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_10_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_10_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_10_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_05_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_05_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_05_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_05_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle1_v0/bugtrap_0/delta_05_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_02_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_02_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_02_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_02_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_02_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_03_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_03_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_03_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_03_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_03_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_05_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_05_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_05_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_05_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_05_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_10_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_10_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_10_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_10_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_10_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_15_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_15_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_15_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_15_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/unicycle2_v0/bugtrap_0/delta_15_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_05_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_05_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_05_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_05_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_05_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_04_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_04_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_04_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_04_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_04_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_10_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_10_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_10_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_10_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_10_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_20_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_20_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_20_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_20_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_20_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_15_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_15_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_15_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_15_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad_bugtrap/delta_15_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_03_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_03_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_03_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_03_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_03_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_04_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_04_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_04_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_04_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_04_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_05_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_05_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_05_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_05_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_05_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_08_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_08_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_08_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_08_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_08_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_10_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_10_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_10_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_10_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_10_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_15_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_15_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_15_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_15_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quad2d_v0/quad2d_recovery_wo_obs/delta_15_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_05_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_05_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_05_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_05_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_05_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_06_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_06_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_06_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_06_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_06_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_15_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_15_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_15_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_15_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_15_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_08_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_08_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_08_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_08_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/window/delta_08_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_05_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_05_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_05_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_05_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_05_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_06_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_06_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_06_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_06_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_06_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_07_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_07_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_07_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_07_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_07_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_08_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_08_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_08_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_08_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_08_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_10_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_10_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_10_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_10_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_10_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_15_v0/idbastar_v0_fixedtime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_15_v0/idbastar_v0_freetime/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_15_v0/idbastar_v0_mpc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_15_v0/idbastar_v0_mpcc/2023-10-24--14-48-48/report.yaml
- ../results_new_timeopt/quadrotor_v0/recovery/delta_15_v0/idbastar_v0_search/2023-10-24--14-48-48/report.yaml
output: ../results_new_timeopt/plots/plot_time_2023-10-24--14-54-32.pdf
selected_guesses:
- quad2d/bugtrap/delta_04_v0
- quad2d/bugtrap/delta_10_v0
- quad2d/recovery_wo_obs/delta_03_v0
- quad2d/recovery_wo_obs/delta_08_v0
- quadrotor_v0/recovery/delta_05_v0
- quadrotor_v0/recovery/delta_10_v0
- quadrotor_v0/window/delta_05_v0
- quadrotor_v0/window/delta_08_v0
- unicycle2_v0/bugtrap_0/delta_05_v0
- unicycle2_v0/bugtrap_0/delta_15_v0
