files:
  - ../results_new/summary/summary_last_merged.csv
benchmark_problems:
  - acrobot_v0/swing_up_empty
  - acrobot_v0/swing_up_obs_hard
  - car1_v0/kink_0
  - car1_v0/parallelpark_0
  - quad2d_v0/fall_through
  - quad2d_v0/quad_bugtrap
  - quad2dpole_v0/up_obs
  - quad2dpole_v0/window_hard
  - quadrotor_v0/recovery
  - quadrotor_v0/recovery_with_obs
  - quadrotor_v1/quad_one_obs
  - quadrotor_v1/window
  - unicycle1_v0/bugtrap_0
  - unicycle1_v2/wall_0
  - unicycle2_v0/bugtrap_0
  - unicycle2_v0/parallelpark_0
benchmark_algs: ["idbastar_v0", "sst_v0", "geo_v0"]
