date: 2023-10-24--10-24-22
hostname: fourier
input:
- ../results_new/unicycle1_v0/parallelpark_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/unicycle1_v0/bugtrap_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/unicycle1_v0/kink_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/unicycle1_v1/kink_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/unicycle1_v2/wall_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/unicycle2_v0/kink_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/unicycle2_v0/parallelpark_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/unicycle2_v0/bugtrap_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/car1_v0/kink_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/car1_v0/bugtrap_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/car1_v0/parallelpark_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2d_v0/empty_0/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2d_v0/empty_1/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2d_v0/quad_obs_column/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2d_v0/quad_bugtrap/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2d_v0/quad2d_recovery_wo_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2d_v0/quad2d_recovery_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2d_v0/fall_through/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/move_with_down/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/move_with_up/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/up/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/down/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/up_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/window_easy/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/window/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quad2dpole_v0/window_hard/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/acrobot_v0/swing_up_empty/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/acrobot_v0/swing_up_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/acrobot_v0/swing_up_obs_hard/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/acrobot_v0/swing_down_easy/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/acrobot_v0/swing_down/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v0/empty_0_easy/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v0/empty_1_easy/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v0/window/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v0/recovery/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v0/recovery_with_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v0/quad_one_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v1/empty_0_easy/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v1/empty_1_easy/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v1/window/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v1/recovery/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v1/quad_one_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
- ../results_new/quadrotor_v1/recovery_with_obs/idbastar_v0/2023-10-24--09-28-26/report.yaml
output: ../results_new/plots/plot_2023-10-24--10-24-22.pdf
